
SIM_TIME = 50

N_SERVERS = 2
CAPACITIES = [2*(i+1) for i in range(N_SERVERS)] 

LB_ALGORITHM = "least_connections" 
OVERHEAD_LEAST_LOAD = 1
OVERHEAD_LEAST_CONNECTIONS = 2

ARRIVAL_RATE = 1.5
TASK_DURATION_MIN = 3
TASK_DURATION_MAX = 6
    